::Const.Strings.RF_AncientDeadCommanderTitles <- [
	"the Returned",
	"the Restorator",
	"the Ancient",
	"the Destroyer",
	"the Herald",
	"the Unearthed",
	"the Honored",
	"the Defender",
	"the Glorious",
	"the Favored"
];
::Const.Strings.CharacterNames.extend([
    "Agnar",
    "Alard",
    "Alaric",
    "Albert",
    "Albterus",
    "Aldwin",
    "Ansgar",
    "Badulf",
    "Baldarich",
    "Baldo",
    "Baldovin",
    "Baldwin",
    "Baranor",
    "Bertilo",
    "Bjorn",
    "Brando",
    "Burchard",
    "Carolus",
    "Cenric",
    "Conrad",
    "Dagfinn",
    "Dunstan",
    "Eckhart",
    "Edgar",
    "Egino",
    "Elof",
    "Emelrich",
    "Eswig",
    "Faramund",
    "Farvald",
    "Filibert",
    "Franco",
    "Friduhelm",
    "Gaufrid",
    "Gautvin",
    "Gerbold",
    "Gilbert",
    "Giselbert",
    "Gismund",
    "Godric",
    "Grimm",
    "Hadubert",
    "Hagano",
    "Harold",
    "Hartwin",
    "Heidrich",
    "Helmfried",
    "Helmo",
    "Helmut",
    "Herman",
    "Kuno",
    "Lambert",
    "Landulf",
    "Lanzo",
    "Leofric",
    "Leonard",
    "Leudagar",
    "Leuthar",
    "Leutwin",
    "Manno",
    "Meino",
    "Meinrad",
    "Milo",
    "Norbert",
    "Odo",
    "Olvir",
    "Oswin",
    "Pipin",
    "Randulf",
    "Regin",
    "Reinald",
    "Reinhard",
    "Richard",
    "Roland",
    "Sigimar",
    "Silvan",
    "Siward",
    "Svenn",
    "Theo",
    "Theodar",
    "Thiemo",
    "Valdemar",
    "Veremund",
    "Waldo",
    "Waldomar",
    "Walther",
    "Widald",
    "Wido",
    "Wigand",
    "Wighart",
    "Wilfred",
    "Wolfhart",
    "Wulfric"
]);

// This removes all duplicate CharacterNames. This line is redundant for Vanilla + Reforged because our additional names are already checked for duplicates
// Any mod that adds names after ours may re-introduce duplicates. This is not game-breaking but still undesired
::Const.Strings.CharacterNames = ::MSU.Array.removeDuplicates(::Const.Strings.CharacterNames);

foreach(characterName in ::Const.Strings.CharacterNames)
{
    ::Const.Strings.KnightNames.push("Sir " + characterName);
}

// This removes all duplicate KnightNames. This is important because Vanilla has KnightNames that also exist as CharacterNames.
::Const.Strings.KnightNames = ::MSU.Array.removeDuplicates(::Const.Strings.KnightNames);

// Remove The Robber Baron as a bandit leader name because we have a RobberBaron entity in Reforged
::MSU.Array.removeByValue(::Const.Strings.BanditLeaderNames, "The Robber Baron");
