::Const.World.LocationNames.RF_DraugrBarrows <- [
	"Barrows of the Old Wyrd",
	"Frozen Cairns",
	"Veiled Barrows",
	"Barrow-Moot Meadows",
	"Snowmarked Ruin",
	"Drowned Hearth Graves",
	"Whisperfen Hollow",
	"Duskfield Graves",
	"Helskeld",
	"Coldshade Hollow",
	"The Howling Mound",
	"Gravenhill",
	"Barrowmark",
	"Oathstone Barrows",
	"Vigil of the First Sons",
	"Ironwake Barrows",
	"Whispering Stones",
	"Ancestor\'s Reach",
	"Elder\'s Hollow",
	"Barrow of the Nine Shields",
	"Sigfrid\'s Longrest",
	"The King\'s Bonehill",
	"Kinmourne Hollow",
	"Grove of Remembering",
	"Dreadwake Mound",
	"Hollow Cairn",
	"Barrow of Ash and Bone",
	"Stonefather’s Mound",
	"Coldwake Barrow",
	"The Shaded Hill",
	"Silentwatch Cairn",
	"Dustbound Hollow",
	"Windgrave",
	"The Elder’s Rest",
	"Wyrdstone Mound",
	"Pale Hearth Barrow",
	"Gravenrise",
	"Whispering Barrow",
	"The Moss-Touched Cairn",
	"Hill of Broken Names",
	"Kinwatch Mound",
	"Rootwound Hollow",
	"Emberrest",
	"The Frost Cairn",
	"The Cracked Barrow",
	"Quietwake",
	"Thawgrave",
	"Hushed Earth",
	"Barrow of Bitter Sleep",
	"The Low Cairn",
	"Rest of the Faded Banner",
	"The Hollow Step",
	"Cairn of the Lost Sons",
	"The Unearthed Place"
];
::Const.World.LocationNames.RF_DraugrCrypt <- [
	"Crypt of the Oath-Bound",
	"Hall of the Flame-Taker",
	"Grave of the Last Duel",
	"The Fellblade Crypt",
	"Chamber of the Unburned",
	"Rest of the Sable Fang",
	"The Broken Shield Crypt",
	"Vault of the Swordfather",
	"Hero’s Hollow",
	"Crypt of Red Valor",
	"Halls of Bitter Triumph",
	"Deepgrave",
	"The War-Sleepers",
	"The Vowkeeper's Vault",
	"Bladewake Crypt",
	"The Thorn-Bound Grave",
	"Vault of the Silver Helm",
	"Stone-Watch of the Dead",
	"Rest of the Storm-Kin",
	"Crypt of the Drowned Banner",
	"Deepwatch Hold",
	"Grave of the Ice-Bitten",
	"Wyrdsinger’s Tomb",
	"Crypt of the Raven-Haired",
	"The Fireless Pyre",
	"Oathstone Chamber",
	"Deathwake Hall",
	"Vault of the Lost Reaver",
	"Ironrest Crypt",
	"The Bound Hall",
	"Thane\'s Rest",
	"Thane\'s Watch"
];
::Const.World.LocationNames.RF_DraugrFane <- [
	"The Wyrd-King’s Fane",
	"Hall of the Broken Line",
	"Fane of the Silent Crown",
	"The Dusk-Hallowed Hall",
	"King’s End Watch",
	"Thronewake",
	"Fane of the Flame-Entombed",
	"The Vault of Kingsunder",
	"Fane of Wyrdstone and Ash",
	"Hall of the Shattered Oath",
	"The Barrowhold",
	"Crowngrave",
	"The Last High Seat",
	"Fane of the Pale King",
	"Hall of the Gilded Bones",
	"Rest of the Kingsblood",
	"The Cold Throne",
	"The Hollow Hall of Vengeance",
	"Fane of the Silent Host",
	"Gravekeep of the Godsworn",
	"Frostwarden Hall",
	"Fane of the Iron Sleep",
	"The Ancestor’s Vigil",
	"The Everwake Fane",
	"Fane of the Burnt Sigil",
	"Dreadwake of the Firstborn",
	"Hall of the Deep Kings",
	"Cryptcourt of the Barrowlord",
	"The Longrest Fane",
	"The Throne Hall"
];

::Const.World.RF_LocationDescriptions <- {};
::Const.World.RF_LocationDescriptions.RF_DraugrBarrows <- [
	"Just a hump of stone in the hills, overgrown and wind-worn. Still, the crows won't go near it.",
	"Some old barrow cracked open by frost or fools. Smells of cold iron and old prayers.",
	"They say it’s just a family mound—but if so, it’s a loud one.",
	"It looks like nothing but a lumpy hill—until you see the stones laid in a circle beneath the moss.",
	"No one's tended the graves for generations, but there's fresh scratch marks on the stones.",
	"One of the men saw smoke curling from the mound at dawn. There’s no chimney under earth, is there?",
	"That’s where the cold seeps from, they say. Cold and something else.",
	"Barbarians used to bury their kin up there. Now they don’t even look that way.",
	"You’ll find old coins and maybe a blade or two in the dirt. Just mind what you wake up reaching for them.",
	"Go ahead and dig—just don’t expect to be the only one moving when the shovel hits stone."
];
::Const.World.RF_LocationDescriptions.RF_DraugrCrypt <- [
	"Locals say a hero sleeps there with his blade across his chest. Others say he's not sleeping anymore.",
	"The place was sealed with a rune-stone none could read. Now the door's open, and something watches from within.",
	"It’s not just bones in that crypt—it’s names, titles, honors long turned sour.",
	"Used to be folks came from leagues around to pay respects. Now even the crows keep their distance.",
	"There’s a name above the lintel, worn smooth by time. Might be best it stayed unread.",
	"That crypt wasn’t just built—it was sealed, like someone wanted what’s inside to stay there for good.",
	"The grave goods were stolen long ago. Or so the last band of thieves said—before they disappeared.",
	"The warriors buried there followed their chieftain even into death. Trouble is, they still do.",
	"You can still see runes on the walls if you bring a torch. Just don’t read them aloud.",
	"Steel echoes down there, like someone’s still practicing with a blade he should’ve laid down centuries ago."
];
::Const.World.RF_LocationDescriptions.RF_DraugrFane <- [
	"Built into the mountain itself—bigger than a lord’s hall, but no fires burn within. Just echoes.",
	"That place was meant to last till the end of the world. Might be the dead inside think it already ended.",
	"They say kings lie there with their tribes. All of them with eyes that never close.",
	"The walls are carved with stories in stone—kings, battles, fires. But the last story never ends.",
	"No one builds like that anymore. Maybe no one should.",
	"The dead there weren’t buried to rest. They were buried to wait.",
	"You hear music sometimes—horns and drums, like a feast starting. There’s no feast.",
	"Even the air inside that mountain feels heavy, like the mountain’s trying to keep its secrets.",
	"A chieftain sleeps there with his entire warband around him. Or maybe they just pretend to sleep.",
	"The bones are dressed in gold and furs, same as in life. And they guard it with the same hands, too."
];
