name: Verify Compilation

on:
  workflow_dispatch:
  pull_request:

jobs:
  compile:
    runs-on: windows-latest

    env:
      MOD_ROOT: ${{ github.workspace }}\
      MOD_PATH: ${{ github.workspace }}\repo
      GAME_PATH: ${{ github.workspace }}\_game_fake

    steps:
      - uses: actions/checkout@v7
        with:
          path: repo

      - name: Setup BBBuilder
        id: bbbuilder
        uses: ./repo/.github/actions/setup-bbbuilder
        with:
          game_path: ${{ env.GAME_PATH }}
          mod_root: ${{ env.MOD_ROOT }}

      - name: Compile Core
        shell: cmd
        working-directory: ${{ steps.bbbuilder.outputs.path }}
        env:
          DOTNET_ROLL_FORWARD: Major
        run: BBbuilder.exe build "%MOD_PATH%" -rebuild -ex "brushes,gfx,music,sounds,scripts/!mods_preload/mod_reforged_assets,scripts/!mods_preload/mod_reforged_patch" -zipname "${{ steps.info.outputs.core_zip }}"
