::Reforged.ItemTable.BanditHelmetBasic <- ::ItemTables.Class.ItemTable([
	[1, "scripts/items/helmets/mouth_piece"],
	[1, "scripts/items/helmets/headscarf"],
	[1, "scripts/items/helmets/hood"],
	[1, "scripts/items/helmets/open_leather_cap"],
	[1, "scripts/items/helmets/aketon_cap"],
	[1, "scripts/items/helmets/full_leather_cap"],
	[1, "scripts/items/helmets/full_aketon_cap"],
	[1, "scripts/items/helmets/rusty_mail_coif"],
	[1, "scripts/items/helmets/rf_scale_helmet"],
	[1, "scripts/items/helmets/nasal_helmet"],
	[1, "scripts/items/helmets/dented_nasal_helmet"],
	[1, "scripts/items/helmets/rf_padded_scale_helmet"],
	[1, "scripts/items/helmets/kettle_hat"],
	[1, "scripts/items/helmets/flat_top_helmet"],
	[1, "scripts/items/helmets/padded_nasal_helmet"],
	[1, "scripts/items/helmets/padded_kettle_hat"],
	[1, "scripts/items/helmets/padded_flat_top_helmet"],
	[1, "scripts/items/helmets/closed_flat_top_helmet"],
	[1, "scripts/items/helmets/closed_flat_top_with_neckguard"]
]);
